### ISSUE TITLE
Parse common escape sequences in arguments

### ISSUE THREAD

**Issue by lytedev** [sflanaga/csv#1]
For example, I have a TSV file (a CSV where the record separator is a tab character) and would like to do the following:

```
< jobs_data.tsv gb -d "\t" ...
```

Or some variation of the same. However, this results in this error:

```
error: Invalid value for '--input_delimiter <delimiter>': too many characters in string
```

Instead, I have to insert an actual tab character (via `^V<TAB>` or `^V^I`) like so:

```
< jobs_data.tsv gb -d "	" ...
```

It'd be great to parse common escape sequences from arguments such as these. Even if not by default, providing a second flag (such as `--parse-escaped-args`) would preserve the existing functionality exactly while providing a potentially aliasable default for anyone preferring this type of behavior.

**Comment by sflanaga** [comment]
bash let's you do a $'\t'
power shell allows a literal `t to be passed
